### ISSUE TITLE
Where to find the BXARM.deb ?

### ISSUE THREAD

**Issue by rertyStrike** [IARSystems/bx-self-hosted-runners#1]
I am trying to follow up the tutorial but I cannot find where it is possible to download the IAR Build Tools installer packages .deb. How can I get it?

**Comment by felipe-iar** [comment]
Hi @rertyStrike, Thanks for pointing the missing information. Our site has been updated recently so the sales contact link became broken. I just updated it now so you can navigate from the [Requirements](https://github.com/IARSystems/bx-self-hosted-runners#requirements) section on the tutorial and click on the [__IAR build tools for Arm 8.50.6__](https://www.iar.com/about/contact/sales/) link from that list.
